import type { Interval, Timer } from '../types';

export const TIMER_NAME_IDEAS = [
  'Certain Death',
  'Call My Mother',
  'Lord Help Me',
  'Hell Is Upon You',
  'Sweat Apocalypse',
  'Pain Express',
  'Doom Circuit',
  'No Mercy Mode',
  'Beast Protocol',
  'Cardio Carnage',
  'Suffer Session',
  'Inferno Intervals',
  'The Burn Zone',
  'Chaos Reps',
  'Death By Burpees',
  'Panic Workout',
  'Last Breath',
  'Rage Routine',
  'Torture Timer',
  'Sweat Storm',
  'The Gauntlet',
  'Agony Engine',
  'Beast Unleashed',
  'Final Countdown',
  'Muscle Mayhem',
  'Oxygen Debt',
  'Scream & Repeat',
  'Savage Sets',
  'Pain Party',
  'Wrecking Mode',
  'Collapse Club',
  'Fire Within',
  'Brutal Beats',
  'End Me Now',
  'No Escape',
  'Grind Time',
  'Cry Later',
  'Heart Attack Lite',
  'War Mode',
  'Kill The Comfort',
  'Max Suffering',
  'Shred Session',
  'Sweat Tsunami',
  'Fear The Timer',
  'Repocalypse',
  'Full Send Fury',
  'No Quit Zone',
  'Suffer Strong',
  'Iron Madness',
  'Push or Perish',
  'Beast Factory',
  'Hurt So Good',
  'The Crusher',
  'Pain Parade',
  'Sweat Symphony',
  'Burn Baby Burn',
  'Gasp & Go',
  'Final Boss Fight',
  'Muscle Meltdown',
  'Chaos Engine',
  'Endurance Trial',
  'No Chill HIIT',
  'Savage Circuit',
  'Panic Mode',
  'Just Survive',
  'The Punisher',
  'Firestorm Fit',
  'Break Yourself',
  'Mad Gains Lab',
  'Sweat Ritual',
  'Last Stand',
  'Cardio Chaos',
  'Total Destruction',
  'The Furnace',
  'Body Breakdown',
  'Rage Against Rest',
  'Absolute Madness',
  'Fight or Flight',
  'Grind & Suffer',
  'The Hurt Locker',
  'Beast Awakens',
  'Scream Session',
  'No Limits',
  'Push Till Failure',
  'Dark Mode HIIT',
  'Pain Threshold',
  'Survival Sets',
  'Burn Protocol',
  'Heartbreaker',
  'Sweat Machine',
  'Endless Reps',
  'Fury Fitness',
  'No Turning Back',
  'Train Insane',
  'Death Circuit',
  'Rise & Grind',
  'Sweat & Regret',
  'Maximum Effort',
  'Embrace The Pain',
] as const;

export const randomTimerName = (random = Math.random): string => {
  const index = Math.floor(random() * TIMER_NAME_IDEAS.length);
  return TIMER_NAME_IDEAS[Math.min(index, TIMER_NAME_IDEAS.length - 1)];
};

export const blankWork = (): Interval => ({
  sequence: 1,
  name: 'Work',
  type: 'work',
  durationMinutes: 0,
  durationSeconds: 30,
});

export const newTimer = (): Timer => {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    name: randomTimerName(),
    sets: 1,
    repeatSetsUntilStopped: false,
    setTransitionMinutes: 0,
    setTransitionSeconds: 30,
    intervals: [blankWork()],
    createdAt: now,
    updatedAt: now,
  };
};
